### ISSUE TITLE
Inquiry for cooperation

### ISSUE THREAD

**Issue by kposavcevic** [hnevkop/eet-kasa#3]
Hi,

We are working on the implementation of EET for one Czech client and we would need help with connecting to Czech Tax Authorities, so we decided to contact you with the hope that you can help us with your esteemed experience.  

At this time, our development team is working on the solution, but we need someone who can help us to connect with Czech Tax Authorities by providing specific local inputs. This would take approximately 3-4 hours of your time per week, depending on the phase of integration. Of course, you would be paid for your time invested.

Please let us know if you are interested in cooperation so we can agree on terms. 

Thank you and best regards, Kristian

**Comment by hnevkop** [comment]
Hello Kristian,

Let's see if I have some capacity for that. What exactly do you need to help with? 
What language/platform etc. ?  So far I did two implementations - integration with EET so I can advise, but I don't consider myself as an expert.
BR,
Premek

**Comment by kposavcevic** [comment]
Hi Premek,

thank you for a quick turnaround! Can you send me your email, so we can move conversation in more details there?

Many thanks,
Kristian

**Comment by hnevkop** [comment]
Hi!

premysl.hnevkovsky@gmail.com

Premek

po 30. 3. 2020 v 17:41 odesílatel kposavcevic <notifications@github.com>
napsal:

**Comment by kposavcevic** [comment]
Hi Premek,

I just sent you an email so we can continue our conversation there. I will close this issue :)

Best,
Kristian
